[0m15:42:49.213008 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108cced50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1093c63f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1093c6030>]}


============================== 15:42:49.216209 | 8430c6d6-656d-4037-b67b-9f42e6065217 ==============================
[0m15:42:49.216209 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:42:49.216606 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/moeinfahmide/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init open_air_dbt', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:42:49.228998 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/moeinfahmide/.dbt')}
[0m15:42:49.229305 [info ] [MainThread]: Creating dbt configuration folder at 
[0m15:42:49.230334 [debug] [MainThread]: Starter project path: /Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/dbt/include/starter_project
[0m15:42:49.234376 [info ] [MainThread]: 
Your new dbt project "open_air_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:42:49.234587 [info ] [MainThread]: Setting up your profile.
[0m15:45:47.821398 [info ] [MainThread]: Profile open_air_dbt written to /Users/moeinfahmide/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:45:47.824615 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 178.6788, "process_in_blocks": "0", "process_kernel_time": 0.140094, "process_mem_max_rss": "107823104", "process_out_blocks": "0", "process_user_time": 0.851268}
[0m15:45:47.824916 [debug] [MainThread]: Command `dbt init` succeeded at 15:45:47.824852 after 178.68 seconds
[0m15:45:47.825151 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1084ca390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094d37d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1093eec60>]}
[0m15:45:47.825367 [debug] [MainThread]: Flushing usage events
[0m15:45:48.287995 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:09:39.056215 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c65ff50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c8c69c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c8c65d0>]}


============================== 18:09:39.061049 | d70eef14-4591-46bb-8697-15e12695e247 ==============================
[0m18:09:39.061049 [info ] [MainThread]: Running with dbt=1.9.4
[0m18:09:39.061651 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/moeinfahmide/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --models stg_airnow_measurements int_sensors', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:09:39.062222 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/moeinfahmide/Desktop/Job/Learning/Data Engineering/projects/open-air/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:09:39.065524 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.08424512, "process_in_blocks": "0", "process_kernel_time": 0.137915, "process_mem_max_rss": "103858176", "process_out_blocks": "0", "process_user_time": 0.97859}
[0m18:09:39.066062 [debug] [MainThread]: Command `dbt run` failed at 18:09:39.065973 after 0.08 seconds
[0m18:09:39.066403 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1050fef30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c049f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bd869c0>]}
[0m18:09:39.066758 [debug] [MainThread]: Flushing usage events
[0m18:09:39.525427 [debug] [MainThread]: An error was encountered while trying to flush usage events
